#!/bin/bash
bar_name="${1:-bar1}"
config_path="$HOME/.config/polybar.old/config"
echo "in Toggle: bar_name = $bar_name"

fallback_monitor="DP-3"

#main_monitor="HDMI-1"
main_monitor="DP3"

all_monitors="$(xrandr --query | grep " connected" | cut -d" " -f1)"

echo "Main Monitor    :  <$main_monitor>"
printf "Fallback Monitor:  <$fallback_monitor>\n\n"

echo "All Monitors:"
printf "$all_monitors\n\n"
readarray -t monitor_array <<< "$all_monitors"

# Function to check if a monitor is in the list
function main_monitor_exists {
	for monitor in "${monitor_array[@]}"; do
		printf "<$monitor>  <$main_monitor>\n"
		if [[ "$monitor" == "$main_monitor" ]]; then
			return 0 # Found
		fi
	done
	return 1 # Not found
}

# Example usage of the function
if main_monitor_exists; then
	echo "$main_monitor is connected."
else
	echo "$main_monitor is not connected."
	main_monitor=$fallback_monitor
	printf "Main monitor was set to fallback monitor | m: $main_monitor | f: $fallback_monitor\n\n"
	#notify-send "Main monitor was set to fallback monitor | m: $main_monitor | f: $fallback_monitor"
fi


#---------------------Top bar---------------------
if [ "$bar_name" = "bar0" ] || [ "$bar_name" = "bar1" ]; then
	if pgrep -a "polybar" | grep "config bar0\|config bar1"; then	
		"$HOME/.config/polybar.old/polykill_bar" "bar0"
		"$HOME/.config/polybar.old/polykill_bar" "bar1"
	else
		MONITOR=$main_monitor polybar --reload --config="$config_path" "bar0" &


		for m in "${monitor_array[@]}"; do
			if [[ "$m" != "$main_monitor" ]]; then
				MONITOR=$m   polybar --reload --config="$config_path" "bar1" &
			fi
		done

	fi
	exit 0
fi




#--------------------Bottom bars-----------------------------

launch_bottom_bar() {
	echo "$bar_name is being launched"

	for monitor in "${monitor_array[@]}"; do
		MONITOR=$monitor   polybar --reload --config="$config_path" "$bar_name" &
	done
	#"$HOME/.config/polybar.old/polylaunch" $bar_name
}



if [ "$bar_name" = "bar2"] ; then
	if pgrep -a "polybar" | grep "config bar2" ; then
		"$HOME/.config/polybar.old/polykill_bar" "bar2"
		"$HOME/.config/polybar.old/polykill_bar" "bar3"
	else    
		"$HOME/.config/polybar.old/polykill_bar" "bar2"
		"$HOME/.config/polybar.old/polykill_bar" "bar3"
		"$HOME/.config/polybar.old/polylaunch" "$bar_name"
	fi
	exit 0
fi

if [ "$bar_name" = "bar3"] ; then
	if pgrep -a "polybar" | grep "config bar3" ; then
		"$HOME/.config/polybar.old/polykill_bar" "bar2"
		"$HOME/.config/polybar.old/polykill_bar" "bar3"
	else
		"$HOME/.config/polybar.old/polykill_bar" "bar3"
		"$HOME/.config/polybar.old/polylaunch" "$bar_name"
		"$HOME/.config/polybar.old/polylaunch" "$bar_name"
	fi
	exit 0
fi



#------------------------Any other bar----------------------------
if pgrep -a "polybar" | grep -e "config $bar_name" ; then
	echo "$bar_name is being killed"
	"$HOME/.config/polybar.old/polykill_bar" $bar_name
	exit 0
else
	echo "$bar_name is being launched"
	"$HOME/.config/polybar.old/polylaunch" $bar_name
	exit 0
fi
