#!/usr/bin/env bash

#must give full bar name

bar_name="${1:-bar1}"

echo "in polykill: The bar name is: $bar_name"
# Terminate already running bar instances

bar_pids=$(pgrep -a polybar | grep "config $bar_name" | awk '{print $1}')

echo "The bar pids are: $bar_pids"

for pid in $bar_pids; do
	kill $pid
	echo "Polybar instance '$bar_name' (PID: $pid) has been terminated"
done





