#!/bin/bash
bar_name="${1:-bar1}"
config_path="$HOME/.config/polybar.old/config"
echo "in Toggle: bar_name = $bar_name"

main_monitor="eDP-1"
#main_monitor="HDMI-1"
#main_monitor="DP-1"

#---------------------Top bar---------------------
if [ "$bar_name" = "bar0" ] ; then
  if pgrep -a "polybar" | grep "config $bar_name"; then
    echo "$bar_name is being killed"
    "$HOME/.config/polybar.old/polykill_bar" "$bar_name"
  else
    echo "$bar_name is being launched"
    MONITOR=$main_monitor polybar --reload --config="$config_path" "$bar_name" &
  fi
  exit 0
fi


if [ "$bar_name" = "bar1" ] ; then
  if pgrep -a "polybar" | grep "config $bar_name" ; then
    "$HOME/.config/polybar.old/polykill_bar" "$bar_name"
  else

    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do

      if [ "$m" != "$main_monitor" ]; then
        MONITOR=$m   polybar --reload --config="$config_path" "$bar_name" &
      fi

    done

  fi
  exit 0
fi

#--------------------Bottom bars-----------------------------

launch_bottom_bar() {
  echo "$bar_name is being launched"
  notify-send "Launching $bar_name"

  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m   polybar --reload --config="$config_path" "$bar_name" &
  done
  #"$HOME/.config/polybar.old/polylaunch" $bar_name
}



if [ "$bar_name" = "bar2"] ; then
  if pgrep -a "polybar" | grep "config bar2" ; then
    notify-send "$bar_name is being killed"
    "$HOME/.config/polybar.old/polykill_bar" "bar2"
    "$HOME/.config/polybar.old/polykill_bar" "bar3"
  elif pgrep -a "polybar" | grep "config bar3" ; then   
    "$HOME/.config/polybar.old/polykill_bar" "bar2"
    "$HOME/.config/polybar.old/polykill_bar" "bar3"
    "$HOME/.config/polybar.old/polylaunch" "$bar_name"
  else
    "$HOME/.config/polybar.old/polykill_bar" "bar2"
    "$HOME/.config/polybar.old/polykill_bar" "bar3"
    "$HOME/.config/polybar.old/polylaunch" "$bar_name"
  fi
  exit 0
fi

if [ "$bar_name" = "bar3"] ; then
  if pgrep -a "polybar" | grep "config bar3" ; then
    notify-send "$bar_name is being killed"
    "$HOME/.config/polybar.old/polykill_bar" "bar2"
    "$HOME/.config/polybar.old/polykill_bar" "bar3"
  elif pgrep -a "polybar" | grep "config bar2" ; then   
    "$HOME/.config/polybar.old/polykill_bar" "bar3"
    "$HOME/.config/polybar.old/polylaunch" "$bar_name"
  else
    "$HOME/.config/polybar.old/polylaunch" "$bar_name"
  fi
  exit 0
fi



#------------------------Any bar----------------------------
if pgrep -a "polybar" | grep -e "config $bar_name" ; then
  echo "$bar_name is being killed"
  "$HOME/.config/polybar.old/polykill_bar" $bar_name
  exit 0
else
  echo "$bar_name is being launched"
  "$HOME/.config/polybar.old/polylaunch" $bar_name
  exit 0
fi
