#!/bin/bash
set -euo pipefail
LOGFILE="$HOME/.config/uwsm/session.log"
exec > >(tee -a "$LOGFILE") 2>&1
echo "=== uwsm session started at $(date) ==="

if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
	echo "Need to manually launch dbus"
	eval "$(dbus-launch --sh-syntax)"
fi

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=Hyprland
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland

export HYPRSHOT_DIR="$HOME/Pictures/Screenshots"
export XCURSOR_SIZE=24
export HYPRCURSOR_SIZE=24

tmux setenv -g HYPRLAND_INSTANCE_SIGNATURE "$HYPRLAND_INSTANCE_SIGNATURE"

# Register with systemd and DBus
dbus-update-activation-environment --systemd --all
systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE

# Background services
/usr/lib/polkit-kde-authentication-agent-1 &
gnome-keyring-daemon --start --components=secrets &
swaync &
# dunst or mako for notif

hyprpaper &
hypridle &

nm-applet &
ironbar &
kanata &

if command -v dex &>/dev/null; then
	dex --autostart --environment "Hyprland"
fi

env >"$HOME/.config/uwsm/env_at_session_start.txt"

# needed because we don't do
# Exec = Exec=uwsm start --pre /home/francois/.config/uwsm/session -- hyprland.desktop
exec Hyprland
